#!/usr/bin/env python3
"""
Region profiler: where do the cycles go in each port, and where do the OCaml builds
lose to C++ - and to each other.

    wsl -d Debian -- python3 tools/profile_regions.py                    # gen, all ports
    wsl -d Debian -- python3 tools/profile_regions.py --mode ppl
    wsl -d Debian -- python3 tools/profile_regions.py --impls cpp
    wsl -d Debian -- python3 tools/profile_regions.py --impls ocaml,oxcaml

Must run inside one Linux environment, for the same reason tools/bench_wsl.sh does:
comparing a WSL binary against a Windows-native one measures the OS and libm.

WHY NOT perf
------------
`perf` needs root to install here, WSL2 exposes no virtualized PMU (so only the
cpu-clock software event works), and flambda2 -O3 inlines the entire forward pass
into one symbol - so symbol-level attribution would report "it is all in
camlMain__forward" and tell us nothing about which chunk is slow. Region counters
read the same TSC in both languages and split the forward pass the same way, which
is the only form of this measurement that is comparable across the two backends.

METHOD
------
The shipped sources are never modified. Instrumented copies are generated by
anchored statement insertion: each edit below quotes real lines from the port and
re-emits them with prof_start/prof_stop around them. Every anchor must match
exactly once, so if either port is edited such that an anchor moves, this tool
fails loudly rather than silently profiling stale code. The regions are the same
seven PORTING.md section 7 used, so the numbers here line up with the Rust column
already published there.

CAVEATS, both real
------------------
1. Observer effect. Two rdtsc reads per region cost roughly 30-60 cycles, and the
   region boundaries act as scheduling barriers that inhibit some cross-region
   optimization. The tool measures the empty-region cost in each binary and
   subtracts it, and reports instrumented vs shipped tok/s so the distortion is
   visible instead of assumed. Small regions (embed) carry the most error.
2. rdtsc counts invariant-TSC reference ticks, not core clocks. Shares and ratios
   are unaffected; absolute cycles/op is off by the turbo ratio.
"""

import argparse
import json
import os
import re
import shutil
import statistics
import subprocess
import sys
import tempfile

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
REGIONS = ["embed", "qkv", "attn", "wo", "mlp", "lm_head", "sample"]

CXXFLAGS = ["-O3", "-std=c++20", "-fno-fast-math", "-ffp-contract=off"]
OPAM_SWITCH = "5.2.0+ox"

# (impl name, opam switch or "" for whatever ocamlopt is on PATH, ocamlopt flags).
# These must match what each port's build.sh ships, or the profile describes a binary
# nobody benchmarks: -O3 is flambda-only, so the stock build does not pass it.
ML_TOOLCHAINS = [
    ("oxcaml", OPAM_SWITCH, "-O3 -unsafe"),
    ("ocaml", "", "-unsafe"),
]

# What each region covers, for the report legend.
LEGEND = {
    "embed":   "wte+wpe sum, then the pre-block rmsnorm",
    "qkv":     "per-layer rmsnorm + wq/wk/wv linears",
    "attn":    "kv-cache write, q.k logits, softmax, value gather",
    "wo":      "output projection + residual add",
    "mlp":     "rmsnorm + fc1 + relu + fc2 + residual",
    "lm_head": "final vocab projection",
    "sample":  "gen: temperature divide + softmax + cumsum draw / ppl: copy + softmax + log",
}


# ------------------------------------------------------------------ preludes

CPP_PRELUDE = r'''// ---------------------------------------------------- region profiler (injected)
// Generated by tools/profile_regions.py. Not part of the shipped port.
#include <x86intrin.h>
#include <cstdlib>

enum { PROF_N = 8 };  // 0..6 are regions; 7 is the calibration scratch
static const char* PROF_NAMES[PROF_N] = {
    "embed", "qkv", "attn", "wo", "mlp", "lm_head", "sample", "calib"};
static unsigned long long prof_t[PROF_N];
static unsigned long long prof_cyc[PROF_N];
static unsigned long long prof_hits[PROF_N];
static unsigned long long prof_ops[PROF_N];
static unsigned long long prof_boot_tsc;
static std::chrono::steady_clock::time_point prof_boot_wall;

#define PROF_START(r) do { prof_t[r] = __rdtsc(); } while (0)
#define PROF_STOP(r, ops) do {                        \
    prof_cyc[r] += __rdtsc() - prof_t[r];             \
    ++prof_hits[r];                                   \
    prof_ops[r] += (unsigned long long)(ops);         \
} while (0)

static void prof_report() {
    // Calibrated here rather than at startup: the empty-region cost has to be measured
    // with the CPU in the same clock state as the run it gets subtracted from.
    const int CAL = 200000;
    prof_cyc[7] = 0;
    for (int i = 0; i < CAL; ++i) { PROF_START(7); PROF_STOP(7, 0); }
    // Program lifetime in both units, so the harness can derive the TSC rate and check
    // what fraction of the run the regions actually account for.
    unsigned long long life = __rdtsc() - prof_boot_tsc;
    double secs = std::chrono::duration<double>(
        std::chrono::steady_clock::now() - prof_boot_wall).count();
    std::fprintf(stderr, "#PROF impl=cpp inflation=%.3f life_cyc=%llu life_sec=%.6f\n",
                 double(prof_cyc[7]) / CAL, life, secs);
    for (int r = 0; r < 7; ++r)
        std::fprintf(stderr, "#PROF region=%s cyc=%llu hits=%llu ops=%llu\n",
                     PROF_NAMES[r], prof_cyc[r], prof_hits[r], prof_ops[r]);
}

namespace {
struct ProfInit {
    ProfInit() {
        prof_boot_wall = std::chrono::steady_clock::now();
        prof_boot_tsc = __rdtsc();
        std::atexit(prof_report);
    }
} prof_init_;
}

'''

ML_PRELUDE = r'''(* ------------------------------------------------- region profiler (injected)
   Generated by tools/profile_regions.py. Not part of the shipped port.
   rdtsc comes from a C stub so this reads the very same counter the C++ build
   reads - a libc clock call here would not be comparable. *)

external rdtsc : unit -> int = "mg_rdtsc" [@@noalloc]

let prof_names = [| "embed"; "qkv"; "attn"; "wo"; "mlp"; "lm_head"; "sample" |]
let prof_t = Array.make 8 0
let prof_cyc = Array.make 8 0
let prof_hits = Array.make 8 0
let prof_ops = Array.make 8 0

let[@inline] prof_start r = prof_t.(r) <- rdtsc ()

let[@inline] prof_stop r ops =
  prof_cyc.(r) <- prof_cyc.(r) + (rdtsc () - prof_t.(r));
  prof_hits.(r) <- prof_hits.(r) + 1;
  prof_ops.(r) <- prof_ops.(r) + ops

let prof_boot_tsc = rdtsc ()
let prof_boot_wall = Unix.gettimeofday ()

let prof_report () =
  let cal = 200000 in
  prof_cyc.(7) <- 0;
  for _ = 1 to cal do
    prof_start 7;
    prof_stop 7 0
  done;
  (* Program lifetime in both units, so the harness can derive the TSC rate and check
     what fraction of the run the regions actually account for. *)
  let life = rdtsc () - prof_boot_tsc in
  let secs = Unix.gettimeofday () -. prof_boot_wall in
  Printf.eprintf "#PROF impl=oxcaml inflation=%.3f life_cyc=%d life_sec=%.6f\n"
    (float_of_int prof_cyc.(7) /. float_of_int cal)
    life secs;
  for r = 0 to 6 do
    Printf.eprintf "#PROF region=%s cyc=%d hits=%d ops=%d\n" prof_names.(r) prof_cyc.(r)
      prof_hits.(r) prof_ops.(r)
  done

let () = at_exit prof_report

'''

C_STUB = r'''/* rdtsc for the OCaml port, so both languages read the same counter. */
#include <caml/mlvalues.h>
#include <x86intrin.h>

value mg_rdtsc(value unit)
{
    (void)unit;
    return Val_long((intnat)__rdtsc());
}
'''


# --------------------------------------------------------------------- edits
# (anchor, replacement). Anchors are verbatim source; each must match exactly once.

CPP_EDITS = [
    # embed
    ("""    for (int i = 0; i < E; ++i) s.x[i] = tok[i] + pos[i];
    rmsnorm(s.x.data(), E, s.x.data());
""",
     """    PROF_START(0);
    for (int i = 0; i < E; ++i) s.x[i] = tok[i] + pos[i];
    rmsnorm(s.x.data(), E, s.x.data());
    PROF_STOP(0, 3 * E);
"""),
    # qkv, then attn starts (the kv-cache write belongs to attn)
    ("""        rmsnorm(s.x.data(), E, s.xn.data());
        linear(s.xn.data(), L.wq, s.q.data());
        linear(s.xn.data(), L.wk, s.k.data());
        linear(s.xn.data(), L.wv, s.v.data());
""",
     """        PROF_START(1);
        rmsnorm(s.x.data(), E, s.xn.data());
        linear(s.xn.data(), L.wq, s.q.data());
        linear(s.xn.data(), L.wk, s.k.data());
        linear(s.xn.data(), L.wv, s.v.data());
        PROF_STOP(1, 2 * E + 3 * E * E);
        PROF_START(2);
"""),
    # attn ends, wo, then mlp starts
    ("""        linear(s.attn.data(), L.wo, s.xn.data());
        for (int i = 0; i < E; ++i) s.x[i] += s.xn[i];

        rmsnorm(s.x.data(), E, s.xn.data());
""",
     """        PROF_STOP(2, 2 * E * T);
        PROF_START(3);
        linear(s.attn.data(), L.wo, s.xn.data());
        for (int i = 0; i < E; ++i) s.x[i] += s.xn[i];
        PROF_STOP(3, E * E);

        PROF_START(4);
        rmsnorm(s.x.data(), E, s.xn.data());
"""),
    # mlp ends at the bottom of the layer loop
    ("""        linear(s.hidden.data(), L.fc2, s.xn.data());
        for (int i = 0; i < E; ++i) s.x[i] += s.xn[i];
    }
""",
     """        linear(s.hidden.data(), L.fc2, s.xn.data());
        for (int i = 0; i < E; ++i) s.x[i] += s.xn[i];
        PROF_STOP(4, 6 * E + 8 * E * E);
    }
"""),
    # lm_head
    ("""    c.len = t_idx + 1;
    linear(s.x.data(), m.lm_head, s.logits.data());
""",
     """    c.len = t_idx + 1;
    PROF_START(5);
    linear(s.x.data(), m.lm_head, s.logits.data());
    PROF_STOP(5, m.vocab_size * E);
"""),
    # sample, generation path
    ("""        ++n;
        for (int i = 0; i < m.vocab_size; ++i)
            tprobs[size_t(i)] = s.logits[size_t(i)] / temperature;
        softmax(tprobs.data(), m.vocab_size);
        token_id = sample_from(tprobs.data(), m.vocab_size, rng, s.cum);
""",
     """        ++n;
        PROF_START(6);
        for (int i = 0; i < m.vocab_size; ++i)
            tprobs[size_t(i)] = s.logits[size_t(i)] / temperature;
        softmax(tprobs.data(), m.vocab_size);
        token_id = sample_from(tprobs.data(), m.vocab_size, rng, s.cum);
        PROF_STOP(6, 5 * m.vocab_size);
"""),
    # sample, scoring path
    ("""        std::memcpy(probs.data(), s.logits.data(), size_t(m.vocab_size) * sizeof(double));
        softmax(probs.data(), m.vocab_size);
        local -= std::log(probs[size_t(t[size_t(pos) + 1])]);
""",
     """        PROF_START(6);
        std::memcpy(probs.data(), s.logits.data(), size_t(m.vocab_size) * sizeof(double));
        softmax(probs.data(), m.vocab_size);
        local -= std::log(probs[size_t(t[size_t(pos) + 1])]);
        PROF_STOP(6, 4 * m.vocab_size);
"""),
]

ML_EDITS = [
    # embed
    ("""  for i = 0 to e - 1 do
    s.x.(i) <- m.wte.d.(tok_base + i) +. m.wpe.d.(pos_base + i)
  done;
  rmsnorm_inplace s.x e;
""",
     """  prof_start 0;
  for i = 0 to e - 1 do
    s.x.(i) <- m.wte.d.(tok_base + i) +. m.wpe.d.(pos_base + i)
  done;
  rmsnorm_inplace s.x e;
  prof_stop 0 (3 * e);
"""),
    # qkv, then attn starts
    ("""    rmsnorm_to s.x s.xn e;
    linear s.xn layer.wq s.q;
    linear s.xn layer.wk s.k;
    linear s.xn layer.wv s.v;
""",
     """    prof_start 1;
    rmsnorm_to s.x s.xn e;
    linear s.xn layer.wq s.q;
    linear s.xn layer.wk s.k;
    linear s.xn layer.wv s.v;
    prof_stop 1 ((2 * e) + (3 * e * e));
    prof_start 2;
"""),
    # attn ends, wo, then mlp starts
    ("""    linear s.attn layer.wo s.xn;
    for i = 0 to e - 1 do s.x.(i) <- s.x.(i) +. s.xn.(i) done;

    rmsnorm_to s.x s.xn e;
""",
     """    prof_stop 2 (2 * e * t_len);
    prof_start 3;
    linear s.attn layer.wo s.xn;
    for i = 0 to e - 1 do s.x.(i) <- s.x.(i) +. s.xn.(i) done;
    prof_stop 3 (e * e);

    prof_start 4;
    rmsnorm_to s.x s.xn e;
"""),
    # mlp ends at the bottom of the layer loop
    ("""    linear s.hidden layer.fc2 s.xn;
    for i = 0 to e - 1 do s.x.(i) <- s.x.(i) +. s.xn.(i) done
  done;
""",
     """    linear s.hidden layer.fc2 s.xn;
    for i = 0 to e - 1 do s.x.(i) <- s.x.(i) +. s.xn.(i) done;
    prof_stop 4 ((6 * e) + (8 * e * e))
  done;
"""),
    # lm_head
    ("""  c.len <- t_len;
  linear s.x m.lm_head s.logits
""",
     """  c.len <- t_len;
  prof_start 5;
  linear s.x m.lm_head s.logits;
  prof_stop 5 (m.vocab_size * e)
"""),
    # sample, generation path
    ("""       incr n;
       for i = 0 to m.vocab_size - 1 do
         (* divide, never a precomputed reciprocal *)
         s.probs.(i) <- s.logits.(i) /. temperature
       done;
       softmax s.probs m.vocab_size;
       token_id := sample_from s.probs m.vocab_size r s.cum;
""",
     """       incr n;
       prof_start 6;
       for i = 0 to m.vocab_size - 1 do
         (* divide, never a precomputed reciprocal *)
         s.probs.(i) <- s.logits.(i) /. temperature
       done;
       softmax s.probs m.vocab_size;
       token_id := sample_from s.probs m.vocab_size r s.cum;
       prof_stop 6 (5 * m.vocab_size);
"""),
    # sample, scoring path
    ("""    Array.blit s.logits 0 s.probs 0 m.vocab_size;
    softmax s.probs m.vocab_size;
    local := !local -. log s.probs.(t.(pos + 1))
  done;
""",
     """    prof_start 6;
    Array.blit s.logits 0 s.probs 0 m.vocab_size;
    softmax s.probs m.vocab_size;
    local := !local -. log s.probs.(t.(pos + 1));
    prof_stop 6 (4 * m.vocab_size)
  done;
"""),
]


def instrument(src, prelude, kernels_marker, edits, what):
    if prelude.strip().splitlines()[0] in src:
        sys.exit(f"{what}: already instrumented?")
    n = src.count(kernels_marker)
    if n != 1:
        sys.exit(f"{what}: kernels marker found {n} times, expected 1")
    out = src.replace(kernels_marker, prelude + kernels_marker)
    for i, (anchor, repl) in enumerate(edits):
        n = out.count(anchor)
        if n != 1:
            sys.exit(f"{what}: edit {i} anchor matched {n} times, expected 1.\n"
                     f"The port was edited and this anchor moved. First line:\n"
                     f"  {anchor.splitlines()[0]!r}")
        out = out.replace(anchor, repl)
    return out


# ------------------------------------------------------------------- builds

def sh(cmd, **kw):
    return subprocess.run(cmd, shell=isinstance(cmd, str), capture_output=True,
                          text=True, cwd=ROOT, **kw)


def build_cpp(src_path, out_path):
    r = sh(["g++"] + CXXFLAGS + ["-o", out_path, src_path])
    return (True, "") if r.returncode == 0 else (False, r.stderr[-3000:])


def build_ml(src_path, stub_path, out_path, switch=OPAM_SWITCH, flags="-O3 -unsafe"):
    """Build an instrumented OCaml binary. `switch` empty means "whatever is on PATH",
    which is how the stock-compiler port is built - see ML_TOOLCHAINS."""
    work = os.path.dirname(src_path)
    setup = (f'eval "$(opam env --switch={switch} 2>/dev/null)" || true\nhash -r'
             if switch else "")
    script = f'''
set -e
{setup}
cd "{work}"
gcc -O2 -c -I"$(ocamlopt -where)" "{stub_path}" -o prof_stub.o
ocamlopt {flags} -I +unix unix.cmxa prof_stub.o "{src_path}" -o "{out_path}"
'''
    r = sh(["bash", "-lc", script])
    return (True, "") if r.returncode == 0 else (False, (r.stdout + r.stderr)[-3000:])


# --------------------------------------------------------------------- runs

def run(cmd, mode, args, pin):
    full = (["taskset", "-c", str(pin)] if pin >= 0 else []) + cmd + [
        "--weights", os.path.join(ROOT, "weights", "microgpt.bin"),
        "--data", os.path.join(ROOT, "data", "val.txt"),
        "--mode", mode, "--samples", str(args.samples), "--seed", "1234",
        "--temperature", "0.5", "--repeats", str(args.repeats),
        "--time-budget", str(args.budget), "--pin", "-1",
    ]
    r = sh(full)
    if r.returncode != 0:
        return None, f"exit {r.returncode}: {r.stderr.strip()[:600]}"
    try:
        rep = json.loads(r.stdout)
    except json.JSONDecodeError as e:
        return None, f"bad JSON on stdout: {e}"
    regions, extra = {}, {}
    for line in r.stderr.splitlines():
        if not line.startswith("#PROF"):
            continue
        kv = dict(m.split("=", 1) for m in line.split()[1:])
        if "region" in kv:
            regions[kv["region"]] = dict(cyc=int(kv["cyc"]), hits=int(kv["hits"]),
                                         ops=int(kv["ops"]))
        else:
            extra = kv
    return dict(report=rep, regions=regions,
                inflation=float(extra.get("inflation", 0.0)),
                life_cyc=float(extra.get("life_cyc", 0.0)),
                life_sec=float(extra.get("life_sec", 0.0)),
                tps=rep[mode]["tokens_per_sec_best"],
                hash=rep.get("gen", {}).get("output_fnv1a64")), None


def split(prof):
    """Per-region raw and empty-pair-corrected cycles, plus how much of the run
    the regions account for at all. Coverage well below 100% would mean the region
    boundaries miss real work and every share below is wrong."""
    infl = prof["inflation"]
    tokens = prof["regions"]["lm_head"]["hits"]   # exactly one lm_head per forward pass
    out = {}
    for name in REGIONS:
        r = prof["regions"][name]
        raw = float(r["cyc"])
        out[name] = dict(raw=raw, cor=max(0.0, raw - r["hits"] * infl),
                         hits=r["hits"], ops=r["ops"],
                         # what fraction of the raw measurement was counter overhead;
                         # a region where this is large is measured badly by definition
                         tax=(r["hits"] * infl / raw) if raw else 1.0)
    raw_tot = sum(v["raw"] for v in out.values())
    cor_tot = sum(v["cor"] for v in out.values())
    for v in out.values():
        v["share"] = v["cor"] / cor_tot if cor_tot else 0.0
    tsc_hz = prof["life_cyc"] / prof["life_sec"] if prof["life_sec"] else float("nan")
    # The instrumented run's own throughput says how many ticks a token really cost;
    # comparing that with the region sum exposes any work falling outside the regions.
    ticks_per_tok = tsc_hz / prof["tps"] if prof["tps"] else float("nan")
    return dict(regions=out, tokens=tokens, raw_tot=raw_tot, cor_tot=cor_tot,
                tsc_hz=tsc_hz, ticks_per_tok=ticks_per_tok,
                raw_per_tok=raw_tot / tokens,
                coverage=(raw_tot / tokens) / ticks_per_tok)


def table(rows, headers, aligns):
    w = [max(len(headers[i]), *(len(r[i]) for r in rows)) for i in range(len(headers))]
    fmt = lambda r: "  ".join(f"{r[i]:{aligns[i]}{w[i]}}" for i in range(len(headers)))
    return "\n".join([fmt(headers), "  ".join("-" * x for x in w)] + [fmt(r) for r in rows])


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--mode", default="gen", choices=["gen", "ppl"])
    ap.add_argument("--impls", default="cpp,oxcaml,ocaml")
    ap.add_argument("--samples", type=int, default=200)
    ap.add_argument("--repeats", type=int, default=3)
    ap.add_argument("--budget", type=float, default=1.0)
    ap.add_argument("--pin", type=int, default=0, help="-1 disables taskset")
    ap.add_argument("--rounds", type=int, default=3,
                    help="repeat the whole measurement and take the median share")
    ap.add_argument("--keep", action="store_true", help="keep the generated sources")
    args = ap.parse_args()

    if os.name == "nt":
        sys.exit("run this inside Linux/WSL: wsl -d Debian -- python3 tools/profile_regions.py")
    want = [i.strip() for i in args.impls.split(",") if i.strip()]

    work = tempfile.mkdtemp(prefix="mgprof-")
    print(f"microgpt region profiler   mode={args.mode}  work={work}")
    print(f"regions: {' '.join(REGIONS)}\n")

    built = {}

    if "cpp" in want:
        src = open(os.path.join(ROOT, "impl", "cpp", "infer.cpp")).read()
        gen = os.path.join(work, "infer_prof.cpp")
        open(gen, "w").write(instrument(src, CPP_PRELUDE,
                                        "// --------------------------------------------------------------- kernels",
                                        CPP_EDITS, "cpp"))
        ok, err = build_cpp(gen, os.path.join(work, "cpp_prof"))
        print(f"build cpp    instrumented {'ok' if ok else 'FAILED: ' + err}")
        if ok:
            built["cpp"] = [os.path.join(work, "cpp_prof")]
        ok2, err2 = build_cpp(os.path.join(ROOT, "impl", "cpp", "infer.cpp"),
                              os.path.join(work, "cpp_ship"))
        print(f"build cpp    shipped      {'ok' if ok2 else 'FAILED: ' + err2}")

    # Both OCaml ports instrument from the SAME anchors, because impl/ocaml/main.ml and
    # impl/oxcaml/main.ml are held byte-identical outside their headers. Profiling them
    # side by side is the only way to see which regions flambda2 actually wins, rather
    # than inferring it from one aggregate tok/s number.
    for name, switch, flags in ML_TOOLCHAINS:
        if name not in want:
            continue
        subdir = os.path.join(work, name)
        os.makedirs(subdir, exist_ok=True)
        src = open(os.path.join(ROOT, "impl", name, "main.ml")).read()
        gen = os.path.join(subdir, "main.ml")
        text = instrument(src, ML_PRELUDE,
                          "(* ----------------------------------------------------------------- kernels",
                          ML_EDITS, name)
        open(gen, "w").write(text.replace("#PROF impl=oxcaml", f"#PROF impl={name}"))
        stub = os.path.join(subdir, "prof_stub.c")
        open(stub, "w").write(C_STUB)
        ok, err = build_ml(gen, stub, os.path.join(subdir, "prof"), switch, flags)
        print(f"build {name:6s} instrumented {'ok' if ok else 'FAILED: ' + err}")
        if ok:
            built[name] = [os.path.join(subdir, "prof")]
        r = sh(["bash", "-lc",
                f'OUT="{subdir}/ship" bash "{ROOT}/impl/{name}/build.sh"'])
        print(f"build {name:6s} shipped      "
              f"{'ok' if r.returncode == 0 else 'FAILED: ' + r.stderr[-800:]}")
    print()

    if not built:
        sys.exit("nothing built")

    # -------- measure: shipped throughput (magnitudes) + instrumented split (shares)
    #
    # Instrumentation slows the two ports by DIFFERENT amounts, because rdtsc is an
    # optimization barrier and GCC had more cross-region optimization to lose than
    # flambda2 did. So the instrumented run is never used for magnitudes - only for the
    # split between regions. Every absolute number below is that split applied to the
    # UNinstrumented binary's measured time per token.
    per_impl = {}
    for name, cmd in built.items():
        ship = (os.path.join(work, "cpp_ship") if name == "cpp"
                else os.path.join(work, name, "ship"))
        prof_runs, ship_tps = [], []
        for _ in range(args.rounds):
            prof, err = run(cmd, args.mode, args, args.pin)
            if err:
                print(f"{name}: instrumented run failed - {err}")
                break
            prof_runs.append(prof)
            if os.path.exists(ship):
                s, serr = run([ship], args.mode, args, args.pin)
                if s:
                    ship_tps.append(s["tps"])
        if not prof_runs or not ship_tps:
            print(f"{name}: skipped (need both an instrumented and a shipped run)")
            continue
        parts = [split(p) for p in prof_runs]
        tps = statistics.median(ship_tps)
        ns_per_tok = 1e9 / tps
        regs = {}
        for r in REGIONS:
            share = statistics.median(x["regions"][r]["share"] for x in parts)
            ops = parts[0]["regions"][r]["ops"] / parts[0]["tokens"]
            regs[r] = dict(share=share, ns=share * ns_per_tok, ops=ops,
                           ns_per_op=share * ns_per_tok / ops if ops else float("nan"),
                           tax=statistics.median(x["regions"][r]["tax"] for x in parts))
        per_impl[name] = dict(
            regs=regs, ns_per_tok=ns_per_tok, tps=tps,
            instr_tps=statistics.median(p["tps"] for p in prof_runs),
            inflation=statistics.median(p["inflation"] for p in prof_runs),
            coverage=statistics.median(x["coverage"] for x in parts),
            tsc_ghz=statistics.median(x["tsc_hz"] for x in parts) / 1e9,
            hash=prof_runs[0]["hash"], ship_hash=None)

    if not per_impl:
        sys.exit("no implementation produced a usable profile")

    # -------- method health, before any conclusions are drawn from it
    print("=" * 96)
    print("METHOD HEALTH  (read this before trusting anything below it)")
    print("=" * 96)
    rows = [[n,
             f"{d['tps']:,.0f}", f"{d['instr_tps']:,.0f}",
             f"{d['instr_tps'] / d['tps'] - 1:+.1%}",
             f"{d['inflation']:.0f}", f"{d['tsc_ghz']:.2f}", f"{d['coverage']:.0%}"]
            for n, d in per_impl.items()]
    print(table(rows, ["impl", "shipped tok/s", "instrumented", "observer effect",
                       "empty-pair cyc", "TSC GHz", "region coverage"],
                ["<", ">", ">", ">", ">", ">", ">"]))
    print("\n  observer effect  how much the counters cost. ASYMMETRIC between these two,")
    print("                   which is why shares - not instrumented times - are used.")
    print("  region coverage  region sum / the instrumented run's real time per token.")
    print("                   Near 100% means the seven regions account for the whole")
    print("                   forward pass; well under means work is escaping them.")

    # -------- per-language profile
    for name, d in per_impl.items():
        print("\n" + "=" * 96)
        print(f"{name.upper()}  region profile  ({args.mode}, {args.rounds} rounds, "
              f"{d['tps']:,.0f} tok/s = {d['ns_per_tok']:.0f} ns/token)")
        print("=" * 96)
        regs = d["regs"]
        rows = [[r, f"{regs[r]['share']:.1%}", f"{regs[r]['ns']:.0f}",
                 f"{regs[r]['ops']:,.0f}", f"{regs[r]['ns_per_op']:.2f}",
                 f"{regs[r]['tax']:.0%}", LEGEND[r]]
                for r in sorted(REGIONS, key=lambda r: -regs[r]["share"])]
        rows.append(["TOTAL", "100.0%", f"{d['ns_per_tok']:.0f}", "", "", "",
                     "one forward pass"])
        print(table(rows, ["region", "share", "ns/tok", "ops/tok", "ns/op", "tax", "covers"],
                    ["<", ">", ">", ">", ">", ">", "<"]))
        bad = [r for r in REGIONS if regs[r]["tax"] > 0.20]
        if bad:
            print(f"\n  'tax' is the share of the raw measurement that was counter overhead"
                  f" and got\n  subtracted back out. Treat {', '.join(bad)} as indicative"
                  f" only - too small to\n  measure cleanly at two rdtsc reads per region.")

    # -------- the actual question: where does the slower port lose to the faster one
    def gap_report(fast, slow, note):
        f, s = per_impl[fast], per_impl[slow]
        gap = s["ns_per_tok"] - f["ns_per_tok"]
        print("\n" + "=" * 96)
        print(f"WHERE {slow.upper()} LOSES TO {fast.upper()}   ns per forward pass; "
              "'of gap' splits the whole slowdown")
        print("=" * 96)
        rows = []
        for r in sorted(REGIONS, key=lambda r: -(s["regs"][r]["ns"] - f["regs"][r]["ns"])):
            c, o = f["regs"][r], s["regs"][r]
            d = o["ns"] - c["ns"]
            rows.append([r, f"{c['ns']:.0f}", f"{o['ns']:.0f}",
                         f"{o['ns'] / c['ns']:.2f}x" if c["ns"] else "-",
                         f"{d:+.0f}", f"{d / gap:+.0%}" if gap else "-",
                         f"{c['ns_per_op']:.2f}", f"{o['ns_per_op']:.2f}"])
        rows.append(["TOTAL", f"{f['ns_per_tok']:.0f}", f"{s['ns_per_tok']:.0f}",
                     f"{s['ns_per_tok'] / f['ns_per_tok']:.2f}x", f"{gap:+.0f}",
                     "100%", "", ""])
        print(table(rows, ["region", f"{fast} ns", f"{slow} ns", f"{slow}/{fast}",
                           "delta", "of gap", f"{fast} ns/op", f"{slow} ns/op"],
                    ["<", ">", ">", ">", ">", ">", ">", ">"]))
        print(f"\n  {note}")

    if "cpp" in per_impl and "oxcaml" in per_impl:
        gap_report("cpp", "oxcaml",
                   "Read 'of gap' first: the share of OxCaml's total slowdown this region\n"
                   "  is responsible for. A region can be 3x slower and not matter (embed), or\n"
                   "  1.6x slower and dominate (mlp). 'ns/op' is the per-float-operation cost,\n"
                   "  which is the codegen-quality signal with problem size divided out.")
    if "cpp" in per_impl and "ocaml" in per_impl:
        gap_report("cpp", "ocaml",
                   "The same split for the stock compiler. Compare it against the OxCaml\n"
                   "  table above region by region: identical source, so every difference\n"
                   "  between the two 'of gap' columns is the middle-end choosing differently.")
    if "oxcaml" in per_impl and "ocaml" in per_impl:
        fast, slow = (("oxcaml", "ocaml")
                      if per_impl["ocaml"]["ns_per_tok"] >= per_impl["oxcaml"]["ns_per_tok"]
                      else ("ocaml", "oxcaml"))
        gap_report(fast, slow,
                   "flambda2 against the closure middle-end on byte-identical source, so\n"
                   "  this table has no language content at all - it is purely which regions\n"
                   "  one compiler codegens better. On the shipped 4-way-unrolled kernel the\n"
                   "  two are close; the gap opens up on the plain kernel, where flambda2 is\n"
                   "  recovering by itself the instruction-level parallelism the unroll\n"
                   "  supplies by hand. See OPTIMIZATIONS.md.")

    if args.keep:
        print(f"\ngenerated sources kept in {work}")
    else:
        shutil.rmtree(work, ignore_errors=True)


if __name__ == "__main__":
    main()
